### ISSUE TITLE
Dead link to YAML Input File API Reference

### ISSUE THREAD

**Issue by rwest** [Cantera/cantera-website#100]
The yaml documentation is giving a 404 error
https://cantera.org/documentation/dev/sphinx/html/yaml/index.html

Dead link in documentation website
![Screen Shot 2020-03-19 at 10 25 29 AM](https://user-images.githubusercontent.com/93807/77077562-c3a6fd80-69cb-11ea-9a4a-5e6b2d4330a1.png)

Also dead links in google.
![Screen Shot 2020-03-19 at 10 27 14 AM](https://user-images.githubusercontent.com/93807/77077735-023cb800-69cc-11ea-9fb8-80c785f6d58e.png)

**Comment by bryanwweber** [comment]
This seems to be fixed now, I'm not sure what the resolution was. Can you confirm @rwest?

**Comment by speth** [comment]
I think we might have an issue with whether the last build that has pushed to cantera.org is the `cantera-website` repo or the `cantera` repo, where the former wipes out the contents of the "dev" docs directory.

**Comment by bryanwweber** [comment]
Yes, I just had that happen with the testing site. I'm not sure why it's doing that, the filter criteria is supposed to exclude that directory.
