### ISSUE TITLE
Link to C++ code in 'ChemEquil.h' is broken

### ISSUE THREAD

**Issue by jaanisark** [Cantera/cantera-website#101]
https://cantera.org/tutorials/python-tutorial.html

Clicking the link for ChemEquil.h [directing to: https://cantera.org/documentation/docs-2.4/doxygen/html/ChemEquil_8h.html] under the Chemical Equilibrium section returns:

> 404: Page Not Found
> 
> What you’re looking for isn’t here.
> 
> Please check the URL.
> 
> If you clicked a link on cantera.org and ended up here, please file an issue on the GitHub repository for this website.

**Comment by bryanwweber** [comment]
Thank you! I'll look into it as soon as I can.
