### ISSUE TITLE
a negative symbol is missing in Plog rate expression in document

### ISSUE THREAD

**Issue by chengdi123000** [Cantera/cantera-website#108]
a negative symbol is missing in Plog rate expression in document on web page: https://www.cantera.org/science/reactions.html#pressure-dependent-arrhenius-rate-expressions-p-log

There should have a negative symbol before the activation energy over R and T.

**Comment by bryanwweber** [comment]
@chengdi123000 any reason to close this? I believe this does need to be fixed

**Comment by bryanwweber** [comment]
@rwest @decaluwe @speth Can I get a sanity check on this issue? Is there a typo in the Chemkin theory manual and our docs, or in the code? I suspect the former, but if someone can confirm I'd feel better 😄

**Comment by rwest** [comment]
I think there should be a negative sign and the chemkin manual is wrong to be missing it.

**Comment by decaluwe** [comment]
That would solve a lot of problems, if reactions were faster at lower temperatures.  A lot of problems... 😂
