### ISSUE TITLE
page not found (https://www.cantera.org/docs/sphinx/html/cython/examples/kinetics_reaction_path.html)

### ISSUE THREAD

**Issue by muthuraj1986** [Cantera/cantera-website#111]
the link shown below is not found

https://www.cantera.org/docs/sphinx/html/cython/examples/kinetics_reaction_path.html

**Comment by bryanwweber** [comment]
Hi! Thanks for reporting this. Where is the link located?

**Comment by muthuraj1986** [comment]
https://mycourses.aalto.fi/login/index.php?lang=en

**Comment by bryanwweber** [comment]
Thanks for the link. Unfortunately, we can't control links on that external website. The equivalent example is here: https://cantera.org/examples/python/kinetics/reaction_path.py.html, I think you'll have to let the site owner know that their link is broken. Thanks for reporting this!
