### ISSUE TITLE
Further updates needed for 2.5.1 release

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera-website#129]
- [x] `2.4.0` in the intro paragraph needs to be replaced: https://testing.cantera.org/documentation/index.html
- [x] `cantera24` references on the macOS install page need to be replaced: https://testing.cantera.org/install/macos-install.html
- [x] `2.4.0` in the intro paragraph needs to be repleaced: https://testing.cantera.org/install/windows-install.html
- [x] Remove recommendation to use Cristoph's wheels page, NumPy has wheels on PyPI now: https://testing.cantera.org/install/windows-install.html
- [x] `Python X.Y` needs to be replaced with `Python 3.X` in the first couple of paragraphs: https://testing.cantera.org/install/windows-install.html
- [ ] Gentoo instructions need to be updated
- [x] Remove suggestion for Cristoph's wheels: https://testing.cantera.org/compiling/installation-reqs.html#sec-installation-reqs
- [x] JQuery should be loaded securely:

     > Mixed Content: The page at 'https://cantera.org/tutorials/python-tutorial.html' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-3.5.1.min.js'. This request has been blocked; the content must be served over HTTPS.
- [x] C++ sample program needs to replace `2.4.0` with `2.5.0`: https://cantera.org/tutorials/cxx-guide/simple-example.html
- [x] Remove Gitter reference: https://cantera.org/community.html
- [x] Update citation: https://cantera.org/community.html
- [x] Update CI to pull the 2.5 branch
- [x] Update the docs parsing plugin to read the stable API docs, instead of pulling from GitHub

**Comment by speth** [comment]
* [ ] Docs for 2.4.0 needs to be added to the list under "Development and Older Versions" on https://testing.cantera.org/documentation/index.html

**Comment by rwest** [comment]
- [ ] "How to cite" at https://cantera.org/community.html#citing-cantera explicitly mentions Version 2.4.0 and has a DOI that points to version 2.4.0 on zenodo.
    - You can cite all versions by using the DOI 10.5281/zenodo.742000. This DOI represents all versions, and will always resolve to the latest one. 
- [ ] Check/update new release metadata on Zenodo (consider a `.zenodo.json` file like [this example](https://github.com/comocheng/cpox/blob/master/.zenodo.json) before tagging the new release?)

**Comment by speth** [comment]
> Update the docs parsing plugin to read the stable API docs, instead of pulling from GitHub

@bryanwweber - I don't see anywhere in `parse_docs.py` that references the development docs specifically. Are the changes that I made to `process_ref_targets.py` what was needed to address this?

**Comment by bryanwweber** [comment]
> Are the changes that I made to `process_ref_targets.py` what was needed to address this?

@speth That's the right spot, but I think the code that pulls from GitHub can be removed because those files are now in the 2.5 api docs folder

**Comment by speth** [comment]
>     * JQuery should be loaded securely:

This is caused by the Nikola template file [bootstrap4-jinja/templates/base_helper.tmpl](https://github.com/getnikola/nikola/blob/master/nikola/data/themes/bootstrap4-jinja/templates/base_helper.tmpl). It's fixed in Nikola's development version (https://github.com/getnikola/nikola/commit/72859b4891910aa7018143527b77d59932b41c1c), but not in any release yet. I'm not sure there's anything we can reasonably do.

**Comment by bryanwweber** [comment]
> I'm not sure there's anything we can reasonably do.

The problem is that it's breaking parts of the site, such as the `copybutton` function that's supposed to allow hiding the prompt characters in the code examples. Bootstrap also relies on JQuery, and I'm not sure if we're using any JS features from Bootstrap.

I'll push a commit that copies the relevant bits from the `base_helper` file temporarily.

**Comment by bryanwweber** [comment]
I think this is closed by #130
