### ISSUE TITLE
Add instructions for installing and using cantera-matlab conda package

### ISSUE THREAD

**Issue by speth** [Cantera/cantera-website#131]
Starting with Cantera 2.5, we now have Matlab packages which can be installed using Conda, (https://anaconda.org/Cantera/cantera-matlab/files) which work on Windows, macOS, and Linux. However, there are no instructions on how to install them, or how to use them once they are installed (i.e., what paths need to be set up in Matlab).

**Comment by bryanwweber** [comment]
Ideally, no paths need to be set up in Matlab! 😄

**Comment by speth** [comment]
How is it possible not to require within Matlab (besides not using the Matlab package...)? 

If I just install the package into a conda environment, it will end up somewhere like `$CONDA_PREFIX\envs\ctmatlab\Library\lib\cantera\matlab\toolbox`, and that needs to be added to the Matlab path, right? Likewise, I think the Cantera data directory needs to be set as well.

**Comment by bryanwweber** [comment]
I'm pretty sure that the installer writes the appropriate paths into the user's `startup.m` file. So the user doesn't need to do anything else, ideally.

**Comment by speth** [comment]
Ah, I didn't remember that it was able to modify `startup.m`. I tried this out, and I'm having trouble with getting it to find the input files on Windows, but I guess that's a separate issue to dig into.
