### ISSUE TITLE
Links from cards broken on many pages

### ISSUE THREAD

**Issue by speth** [Cantera/cantera-website#138]
With the update triggered by merging #136, the website is no longer correctly rendering "cards" on many (but not all) pages, and what is rendered no longer has a working link. For example, the "Tutorials" page now shows this:
![image](https://user-images.githubusercontent.com/644977/113903448-01292500-979f-11eb-89d2-f4c9e6971bca.png)

Some pages are fine, though. For example, the "Science" page:
![image](https://user-images.githubusercontent.com/644977/113903621-2ddd3c80-979f-11eb-852c-42ae8d7647c8.png)

**Comment by bryanwweber** [comment]
The problem is caused by the recent release of docutils 0.17. I've pinned 0.16 in #139.
