### ISSUE TITLE
Conda installation instructions should mention 64-bit requirement

### ISSUE THREAD

**Issue by speth** [Cantera/cantera-website#143]
As long as Anaconda and Miniconda are distributing 32-bit installers, we should clearly indicate that you have to use a 64-bit conda to install Cantera.

**Comment by bryanwweber** [comment]
I think this is only for Windows, right?

**Comment by speth** [comment]
Mostly, though not entirely. Miniconda still provides a 32-bit installer for Python 3.7 on Linux (with 64-bit installers only available for Python 3.8 and 3.9). This is also related to #142, since some people will have legacy installations of 32-bit conda. It looks like the last release of Anaconda that had a 32-bit Linux installer was at the end of 2018, which isn't all that long ago.
