### ISSUE TITLE
Links to some C++ examples are broken (404)

### ISSUE THREAD

**Issue by speth** [Cantera/cantera-website#147]
From https://cantera.org/examples/cxx/index.html, the automatically-generated links to the following examples are broken:
* "Gas phase transport properties" links to https://cantera.org/examples/cxx/gas%20transport.html
* "LiC6 Electrode" links to https://cantera.org/examples/cxx/LiC6%20electrode.html
* "Ignition delay calculation with OpenMP" links to https://cantera.org/examples/cxx/openmp%20ignition.html

In each case, the space (encoded as `%20`) should actually be a dash.

**Comment by bryanwweber** [comment]
Fixed by @chinahg in #150
