### ISSUE TITLE
Location of input files used in Jupyter examples is not obvious

### ISSUE THREAD

**Issue by speth** [Cantera/cantera-website#148]
If a user starts from a Jupyter example shown on the Cantera website, e.g. https://cantera.org/examples/jupyter/reactors/1D_pfr_surfchem.ipynb.html, that requires an input file that's not distributed with the Cantera Python module, it's really not clear where the user should look to find these input files. Some information on the landing page (https://cantera.org/examples/jupyter/index.html) would be a start, but I think it would be even better to provide links to these input files on the pages with the individual examples.

This issue was identified as part of a discussion on the [Users' Group](https://groups.google.com/g/cantera-users/c/26fcss8-Sg4).

**Comment by ischoegl** [comment]
I think that would be a great idea. It may make sense to collect all data files in the root folder of the jupyter repo (after conversion to YAML), which would make it easier to point to just one location.
