### ISSUE TITLE
Add/link Fortran documentation

### ISSUE THREAD

**Issue by mefuller** [Cantera/cantera-website#155]
cantera-website/pages/documentation/dev-docs.html has no links for Fortran documentation - does it exist somewhere and needs to be linked or does it need to be documented and written up?
(I have a potential project in mind for which I would like to use the Fortran interface - I could potentially work developing the documentation if needed)

**Comment by bryanwweber** [comment]
Thanks @mefuller, there is currently no documentation for the fortran interface that I'm aware of. Adding some world be awesome!

**Comment by speth** [comment]
I think we can regard this as superseded by Cantera/enhancements#116.
