### ISSUE TITLE
Make Python WallBase Documentation 

### ISSUE THREAD

**Issue by stijn76** [Cantera/cantera-website#156]
Hi!

The python documentation on the cantera website is missing any information on the WallBase class. Yet this would be convenient to figure out how to get the values for e.g. the wall area and heat flux (qdot(t)). I had to go to the class files to figure out, now. Not sure if there is an easy way to perhaps automatically generate such documentation?

Many thanks for taking this into consideration! 

Best regards,

Stijn

**Comment by bryanwweber** [comment]
As @ischoegl said, there is C++ documentation generated, and documentation is present for the `Wall` class in Python. I'm going to close this; @stijn76 please feel free to reopen with a comment as to how this can be clarified!
