### ISSUE TITLE
Add the equivalent of the doxylink functionality

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera-website#16]
To allow easy linking to C++ documentation

https://github.com/sphinx-contrib/doxylink/blob/master/sphinxcontrib/doxylink/doxylink.py

**Comment by ischoegl** [comment]
Sphinx and doxygen content that are generated from the main repo have - at this point - functional doxylink capabilities. Given the direction of Cantera/enhancements#178, I believe this can be closed? (If there is something that I am overlooking, please reopen)
