### ISSUE TITLE
Documentation doesn't explain how to run with matlab (octave)

### ISSUE THREAD

**Issue by yurivict** [Cantera/cantera-website#168]
It seems that documentation focuses on specific functions and doesn't cover topics like how to run it in the first place.

For example:
```
$ octave  flame1.m 
'flame1' is a script from the file /home/yuri/cantera/flame1.m

 FLAME1 - A burner-stabilized flat flame

    This script simulates a burner-stablized lean hydrogen-oxygen flame
    at low pressure.


Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at https://www.octave.org and via the help@octave.org
mailing list.
error: 'oneatm' undefined near line 13, column 13
error: called from
    flame1 at line 13 column 12
```

```addpath /usr/local/lib/cantera/matlab``` was executed, so it isn't clear what's wrong, and the documentation doesn't help either.

**Comment by yurivict** [comment]
Does Matlab also require to add the ```addpath``` line to some file before the package can be used?

**Comment by bryanwweber** [comment]
Yes, usually it can go in `startup.m`, or using the GUI interface you can add the appropriate folder, which I think adds it to some system directories.

**Comment by bryanwweber** [comment]
@yurivict Do you plan to add these instructions for FreeBSD?

**Comment by yurivict** [comment]
The FreeBSD port already runs with Octave - no instructions are needed there.

**Comment by bryanwweber** [comment]
Thanks @yurivict I'll close this issue then. Please feel free to reopen if there is something that still needs to be done here
