### ISSUE TITLE
Electrochemical Reactions missing from Science Section

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera-website#172]
While [ElectrochemicalReaction](https://cantera.org/documentation/docs-2.5/doxygen/html/d6/ddd/classCantera_1_1ElectrochemicalReaction.html)s have their own Cantera class definition, there is no corresponding section in the [Science Section](https://cantera.org/science/reactions.html) on the website.

**Comment by decaluwe** [comment]
Thanks. I’ll put it on my to-do list 😁

**Comment by ischoegl** [comment]
Let’s hold that thought. Extrapolating from Cantera/cantera#1183 this may not be a specialization once I’m done with Cantera/cantera#1181 any longer. There is, however, a need to document this somehow eventually.
