### ISSUE TITLE
Reformatting Reactors and Reactor Networks science page for clarity

### ISSUE THREAD

**Issue by chinahg** [Cantera/cantera-website#175]
Current Reactors and Reactor Networks science page is very long and does not provide clear information on which governing equations correspond to each reactor type. 

Proposing formatting changes to simplify user interface. Possibly separate pages for each reactor type including delegated reactors (using reactor science page as a home base for hyperlinks). Reactor networks will also have a separate, linked, page that includes integration documentation. Walls, surface reactions, and flow devices will remain on initial Reactor science page. Ideally also include diagrams to clarify what each variable in the governing equations are.

**Comment by speth** [comment]
I think this is done now that #189 has been merged.
