### ISSUE TITLE
Add documentation for covered configuration options

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera-website#177]
The new GitHub CI covers a few common configuration options for a compilation of Cantera from source. It would be good to document what is routinely tested, and what is not covered by the test runners.

Issue is opened in response to discussion in Cantera/cantera#1208

**Comment by speth** [comment]
For this, were you thinking about which options to `scons` are covered by the CI tests, which versions of various dependencies are covered, or, I suppose, both?

There's at least an attempt at documenting the tested versions of dependencies on https://cantera.org/compiling/dependencies.html#sec-dependencies, though that is always kind of a challenge to keep updated.

**Comment by bryanwweber** [comment]
This issue was opened specifically to document that MSVC 12.0 (VS 2013) is not tested, although it will likely work. So I think the intention is to document dependency versions. I think trying to document which SCons options are tested isn't as useful for users, although having some code coverage on the SCons scripts would be useful for developers...

**Comment by ischoegl** [comment]
> For this, were you thinking about which options to scons are covered by the CI tests, which versions of various dependencies are covered, or, I suppose, both?

Both. It’s probably something where finding the right layout will go a long way, as I think documenting what is tested on what platform is also interesting to users. I had admittedly forgotten about that page, but it also isn’t exactly what @bryanwweber was asking about when this came up.

**Comment by ischoegl** [comment]
Closing - this is probably not a priority, especially as keeping this updated is an unnecessary chore.
