### ISSUE TITLE
Document installation/use of libcantera-devel conda package

### ISSUE THREAD

**Issue by speth** [Cantera/cantera-website#180]
We need some documentation of:
- What this package provides
- What platforms are supported / current limitations
- How to install it
- How to use it when compiling / linking C++ (or Fortran?) applications

**Comment by ischoegl** [comment]
I am not sure that documentation should be included at the moment. This will leave the option to discuss the future of this (at the moment likely infrequently used) package after the 2.6 release. Currently, the package doesn't work on windows (see Cantera/conda-recipes#20), and there may be additional steps required to make it useful (see Cantera/enhancements#140).

**Comment by bryanwweber** [comment]
I think it would be worth documenting the cases that work, at least Linux where (I suspect) this is most likely to be used. If anything, I think we would only drop this package for Windows but leave the other two platforms that are easier to support.
