### ISSUE TITLE
Some text is duplicated between C++ documentation and science

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera-website#20]
It wasn't always very clear where to put content when splitting this, so try to deduplicate somewhat

**Comment by bryanwweber** [comment]
Also, move science content out of the C++ documentation into the `science` section

**Comment by speth** [comment]
I think all of the duplication in the CTI tutorial was removed as part of #91. Should the title of this issue be changed to indicate that only this second concern about the science content in the C++ documentation still needs to be done?

**Comment by ischoegl** [comment]
Superseded by Cantera/enhancements#178
