### ISSUE TITLE
Broken link to NASA Polynomials Species Thermo entry

### ISSUE THREAD

**Issue by SRWoolston** [Cantera/cantera-website#207]
On the page https://cantera.org/science/thermodynamics.html, the link to the NASA Polynomials Species Thermo page (https://cantera.org/science/science-species.html#the-nasa-7-coefficient-polynomial-parameterization) produces a 404 error.

**Comment by ischoegl** [comment]
Should be https://cantera.org/science/species-thermo.html#the-nasa-7-coefficient-polynomial-parameterization ... thanks for pointing this out!
