### ISSUE TITLE
Move docs and dev-docs out of api-docs folder to make updating easier

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera-website#21]
I think the `docs` and `dev-docs` submodules should no longer be submodules, but instead should be their own repos at the same level as the main website repo (this repo), so the file tree looks like

```
|- /home/user/repos
|--- cantera-website
|--- dev-docs
|--- docs
```
This way, the Travis build can push to the `dev-docs` and the `cantera-website` repos using ssh (similar to how it's being done to push to GitHub). (To do this, we'll need to enable a configuration option on these repositories locally: https://blog.github.com/2015-02-06-git-2-3-has-been-released/). I think it makes most sense to manually push/pull in the docs repo, since that will only be updated for tagged releases.

Then we have a [`post-receive`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) hook in the `dev-docs` and `cantera-website` repos on cantera.org that triggers a rebuild of the website and copies the output of the build to the appropriate directory to be served. One potential challenge of this is handling failed builds - one reason to do this only after pushing from Travis is the build should fail on Travis first, so the code won't ever be pushed. Another challenge is that the push from Travis doesn't release the connection until the `post-receive` script finishes, so we'd need to find a way to work around that.

**Comment by speth** [comment]
I'm not sure that keeping the compiled documentation as Git repositories is actually desirable. I had originally started posting them that way before we had access to the `cantera.org` domain with a server to go along with that.

**Comment by bryanwweber** [comment]
So just build the documentation on-demand on the `cantera.org` server?

**Comment by bryanwweber** [comment]
f74bd9896817469c802b0213b516cdc150e9c3a3 deleted the two submodules from `api-docs`

**Comment by bryanwweber** [comment]
The resolution to this is to build the website on Travis from this repo and `rsync` it to the `cantera.org` server. The `dev-docs` are built from a Travis build of the main Cantera repo and also `rsync`ed directly to the `cantera.org` server.
