### ISSUE TITLE
Nikola build broken

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera-website#218]
At the moment, the website does not build with some cryptic `yapsy` issue - see [build log](https://github.com/Cantera/cantera-website/runs/7537414880?check_suite_focus=true)

PS: it looks like an upstream issue, so hopefully this will clear before long.

**Comment by bryanwweber** [comment]
I forgot to add this in the commit message, but I think pinning is the appropriate resolution rather than waiting for upstream since we'll be dropping this dependency once we switch to Sphinx.
