### ISSUE TITLE
Alterations to Windows MATLAB install instructions

### ISSUE THREAD

**Issue by simonpickering** [Cantera/cantera-website#241]
I've just installed Cantera (2.6.0) for use with MATLAB 2022b under Windows 10.

I followed these instructions:
https://cantera.org/install/windows-install.html#sec-install-windows

At the bottom of that page in the "Test Installation" section it says to run the following:

`gas = IdealGasMix('gri30.yaml')`

However, MATLAB cannot find this function and nor can I when searching the toolbox folder/subfolders. From a quick Google search it looks like this function may no longer be supported? If so, it would be worth removing this from the page/specifying that it's only for an earlier version of Cantera.

Skipping that function, I tried the next one:

`h2o = Solution('liquidvapor.yaml', 'water')`

Which worked fine once I'd manually created the environemental variable that MATLAB warned me may be needed: CANTERA_DATA=C:\Program Files\Cantera\data
If I remember correctly the error message indicated that this may be because the install was not completed correctly, however, it appeared to have worked without error so it would probably be worth adding the creation of the environmental variable to the instructions.

**Comment by speth** [comment]
The first issue, regarding the deprecated/removed `IdealGasMix` method, is resolved by #246.

If you used the Cantera MSI installer, the installation directory is written to the registry, and Cantera automatically adds that directory to its data file search path. I tested this with the latest installers generated for Cantera 3.0.0a5, and they seem to work correctly.

If you (or anyone else) finds it necessary to set `CANTERA_DATA` after using the MSI, it would help to get the complete error message text.
