### ISSUE TITLE
Mole-based reactors are undocumented

### ISSUE THREAD

**Issue by speth** [Cantera/cantera-website#244]
The governing equations for the mole-based reactor types (`MoleReactor`, `ConstPressureMoleReactor`, `IdealGasMoleReactor`, and `IdealGasConstPressureMoleReactor`) need to be documented here: https://cantera.org/science/reactors/reactors.html#reactor-types-and-governing-equations.

@anthony-walker, can you help with this?

**Comment by ischoegl** [comment]
@anthony-walker ... while this is on the main repository, could you also add a little to docstrings handled by Doxygen? 

* [PreconditionerBase](https://cantera.org/documentation/dev/doxygen/html/d1/d50/classCantera_1_1PreconditionerBase.html) and [Reactor::Jacobian](https://cantera.org/documentation/dev/doxygen/html/d9/d08/group__derivGroup.html#ga8608986baffc99bb53074864c2d73cef)
* `MoleReactor` specializations do not have "brief" docstrings, as evident under the "Classes" section in the [Reactor overview](https://cantera.org/documentation/dev/doxygen/html/dc/d14/group__reactorGroup.html)

**Comment by anthony-walker** [comment]
@ischoegl I will have a look.

**Comment by ischoegl** [comment]
> @ischoegl I will have a look.

Thank you! One thing we just added is the Doxygen `@cite` feature to support BibTeX citations. See https://cantera.org/documentation/dev/doxygen/html/d0/de3/citelist.html
