### ISSUE TITLE
Stable documentation (2.6) points to development C++ Reference

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera-website#250]
**Problem description**

Following a link in a [recent UG question](https://groups.google.com/g/cantera-users/c/bQns_POr7xQ/m/viEPbTezAwAJ), it becomes apparent that there is a mismatch of version between documentations (which after https://github.com/Cantera/cantera/pull/1546 becomes a lot more apparent than it was in the past).

The link in the referenced document is https://cantera.org/documentation/dev/doxygen/html/d3/dd6/classCantera_1_1UnityLewisTransport.html#details
which originates here: https://github.com/Cantera/cantera/blob/5f1014c1a0c3f710db0cc2448e47bacddbb4617d/doc/sphinx/yaml/phases.rst?plain=1#L137-L149

There appear to be quite a few other instances where reST files point to the wrong version.

**Additional context**

While this *appears* to be a website issue, the offending documentation is part of the main repository.

**Comment by ischoegl** [comment]
For the upcoming release, this is addressed by `doxylink` references introduced in Cantera/cantera#1572

**Comment by speth** [comment]
Can we close this issue? I don't think going back and fixing links in 2.6 documentation would be a good use of time.

**Comment by ischoegl** [comment]
👍
