### ISSUE TITLE
Description of the governing equations for specific reactor

### ISSUE THREAD

**Issue by lganeshs** [Cantera/cantera-website#252]
Hi,

I am unable to access the Cantera page with the description of equations for Reactor class. Any idea on where it can be fornd. I would like to modify the equations using ExtensibleReactor option

**Comment by ischoegl** [comment]
Please check 

https://cantera.org/science/reactors/reactors.html

and

https://cantera.org/science/reactors/extensiblereactor.html

for additional questions, please use the user group.
