### ISSUE TITLE
Typo in reaction rate docs

### ISSUE THREAD

**Issue by speth** [Cantera/cantera-website#262]
"Elementary" reactions are incorrectly described as being automatically detected as third body reactions on this page: https://cantera.org/science/kinetics.html

Originally reported here: https://groups.google.com/g/cantera-users/c/4ARX81IfgZk

**Comment by ischoegl** [comment]
Not necessarily a typo, as it states: “In case the type entry is omitted and **a species occurs on both sides,** Cantera infers that the reaction type is three-body.” None of the reactions posted on the UG meet this criterion.  This doesn’t mean that we can’t improve the wording, though …
