### ISSUE TITLE
Need to add a site-wide search

### ISSUE THREAD

**Issue by speth** [Cantera/cantera-website#34]
Currently, the only search options available are in the Documentation section, one for the Sphinx/Matlab docs and one for the Doxygen docs. However, with the idea of moving more documentation to the Science section of this site, being able to search all of this content will become more important.

**Comment by bryanwweber** [comment]
Algolia might be a good option: https://www.algolia.com/doc/api-client/getting-started/install/python/

**Comment by bryanwweber** [comment]
Even better, here's an open-source thing that seems really simple: https://stork-search.net/

**Comment by bryanwweber** [comment]
See here too: https://bart.degoe.de/building-a-full-text-search-engine-150-lines-of-code/

**Comment by bryanwweber** [comment]
Superseded by #210
