### ISSUE TITLE
404: Page Not Found

### ISSUE THREAD

**Issue by vahidmech** [Cantera/cantera-website#35]
From the following address:
https://cantera.org/tutorials/python-tutorial.html

where the following sentence is written 
See the Converting CK-format Files documentation for information on how to convert from Ck-format to CTI format.

By clicking on "Converting CK-format Files" it goes 404: Page Not Found

The correct hyperlink is "https://cantera.org/tutorials/ck2cti-tutorial.html"

**Comment by bryanwweber** [comment]
Thank you!
