### ISSUE TITLE
Add detailed changelog link to documentation page

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera-website#38]
We would like to publish the detailed change logs that we generate for each release on the website. These detailed change logs contain comments for nearly all of the git commits and pull requests since the last release. The links to the change logs could be in the "Other documentation" section of the main Documentation page.

I think the best way to solve this issue is to write a plugin that automatically takes a markdown file with git hashes, GitHub usernames, and GitHub issue/PR numbers and writes the correct links. The markdown file with the change log should be stored in the repository for the website somewhere, perhaps in a `posts/changelogs` directory.

**Comment by bryanwweber** [comment]
https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/

**Comment by HAKSOAT** [comment]
@bryanwweber I'm interested in working on this project. Any extra information I may need to write a proposal?

**Comment by bryanwweber** [comment]
@HAKSOAT Please see the GSoC ideas page for more information: https://github.com/Cantera/cantera/wiki/GSoC-2019-Ideas Note that addressing only this issue in your GSoC proposal will not be sufficient for it to be successful.

**Comment by bryanwweber** [comment]
This was completed by #95
