### ISSUE TITLE
The link given in the matlab and python tutorials is no longer exist.

### ISSUE THREAD

**Issue by nishikeshKardak** [Cantera/cantera-website#55]
### Descibe the bug
The link for *GRI- Mech 3.0, the 53-species, 325-reaction natural gas combustion mechanism* given in the python and Matlab tutorial is no longer exist. The website shows error 404.

### Scrrenshots
![Capture7](https://user-images.githubusercontent.com/39300717/54068667-46ec2a00-4275-11e9-8ddb-53f036c0eeec.JPG)

### Versions
OS: windows
Browser: Chrome

**Comment by bryanwweber** [comment]
Hi, thanks for this report. Can you link to the page where this is broken? The link that I see (http://www.me.berkeley.edu/gri_mech/) seems to work for me

**Comment by nishikeshKardak** [comment]
> Hi, thanks for this report. Can you link to the page where this is broken? The link that I see (http://www.me.berkeley.edu/gri_mech/) seems to work for me

Hello @bryanwweber, this link still not work for me. I comment link of pages where this link(http://www.me.berkeley.edu/gri_mech/) is present.
[Python tutorial](https://cantera.org/tutorials/python-tutorial.html)
[Matlab tutorial](https://cantera.org/tutorials/matlab-tutorial.html)

**Comment by bryanwweber** [comment]
That's very strange. On my laptop it works fine, but on my desktop I get the same 404. Could you please submit a PR to fix this?

**Comment by nishikeshKardak** [comment]
Thanks sir for reply. Currently I'm working on that. I will make PL to fix this.

**Comment by bryanwweber** [comment]
The redirected link seems to be http://combustion.berkeley.edu/gri-mech/

**Comment by nishikeshKardak** [comment]
This issue solved by PL #59
