### ISSUE TITLE
The buttons in Installation Requirements page are of different sizes

### ISSUE THREAD

**Issue by agarwalrounak** [Cantera/cantera-website#63]
The page at https://cantera.org/compiling/installation-reqs.html has buttons of different sizes according to the length of the OS which looks quite odd. They should be of the same size for better User Experience.
![image](https://user-images.githubusercontent.com/38394281/54268354-02c49680-45a1-11e9-9967-01ffb100a895.png)

#### Are you working on the issue?
Yes

**Comment by agarwalrounak** [comment]
@bryanwweber Should I start working on this?

**Comment by bryanwweber** [comment]
Sure, this seems like a reasonable change
