### ISSUE TITLE
Link to documentation for the current version of Cantera is wrong

### ISSUE THREAD

**Issue by agarwalrounak** [Cantera/cantera-website#69]
The documentation for older versions of Cantera have link to wrong documentation for the current version of Cantera. In [Cantera 2.2.1](https://cantera.org/documentation/docs-2.2/sphinx/html/index.html), [Cantera 2.1.2](https://cantera.org/documentation/docs-2.1/sphinx/html/index.html) and [Cantera 2.0.2](https://cantera.org/documentation/docs-2.0/sphinx/html/index.html), `here` in `Documentation for the current version of Cantera is available here` redirects to [Cantera 2.3.0](https://cantera.org/documentation/docs-2.3/sphinx/html/index.html) which is also an older version.

#### Are you working on the issue?
Yes

**Comment by bryanwweber** [comment]
Since we have the alert box now, I think deleting that text is the appropriate course of action. You can look at the `api-docs/add_warning.py` file for an example of how I added the warning alert box to each page.
