### ISSUE TITLE
updated NumFOCUS donation link

### ISSUE THREAD

**Issue by lisamartin72** [Cantera/cantera-website#70]
Hi, I am a new staff member at NumFOCUS. We have updated our donation provider from Flipcause to Salsa. The new link is: 

https://numfocus.salsalabs.org/donate-to-cantera/index.html

Please update your website accordingly. : )

I also noted that you have the old flipcause link in a number of your other repos as well.

Thanks, 

Lisa Martin
NumFOCUS

**Comment by nishikeshKardak** [comment]
Hello @bryanwweber, Can I work on this issue??

**Comment by bryanwweber** [comment]
Hi @lisamartin72! Welcome to NumFOCUS! We got the email from @Dr-G yesterday, this is being fixed in #58 (specifically ed75a1a) for the website, and I'll make sure to update our other repos. Thank you!

@nishikeshKardak No, I've got this, thanks!

**Comment by bryanwweber** [comment]
Hi @lisamartin72, I think I've fixed all the places where we had the Flipcause link. I only noticed it in our website here and in one place in our main Cantera/cantera repository (in the docs). Were there other places that you noted?
